"""non_clinical_info table

Revision ID: 03b7f33fb3f2
Revises: c567b76b8906
Create Date: 2022-04-12 15:20:18.829425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b7f33fb3f2'
down_revision = 'c567b76b8906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'non_clinical_info', ['drug_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'non_clinical_info', type_='unique')
    # ### end Alembic commands ###
