"""token table

Revision ID: 4c574963d2bc
Revises: 62eb69a5fdf6
Create Date: 2022-04-05 21:18:44.829012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c574963d2bc'
down_revision = '62eb69a5fdf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'token', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='unique')
    # ### end Alembic commands ###
