"""token table

Revision ID: 62eb69a5fdf6
Revises: 0a48767bf202
Create Date: 2022-04-05 04:10:10.492130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62eb69a5fdf6'
down_revision = '0a48767bf202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('expiry', sa.DateTime(), nullable=True))
    op.add_column('token', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'status')
    op.drop_column('token', 'expiry')
    # ### end Alembic commands ###
