"""users table

Revision ID: 9af1c60fe749
Revises: c97876c29dc4
Create Date: 2022-03-15 13:15:48.728967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9af1c60fe749'
down_revision = 'c97876c29dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
