"""manufacturer table

Revision ID: c567b76b8906
Revises: 4c574963d2bc
Create Date: 2022-04-12 08:17:16.906212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c567b76b8906'
down_revision = '4c574963d2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'manufacturer', ['drug_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manufacturer', type_='unique')
    # ### end Alembic commands ###
